a = int(input("Enter 1st number : "))
b = int(input("Enter 2nd number : "))
c = int(input("Enter 3rd number : "))
print("Sum of these 3 numbers :",a+b+c)
print("Multiplication of these 3 numbers :",a*b*c)
